{% set name = "pydocstyle" %}
{% set version = "6.0.0" %}
{% set hash = "164befb520d851dbcf0e029681b91f4f599c62c5cd8933fd54b1bfbd50e89e1f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - pydocstyle = pydocstyle.cli:main


requirements:
  host:
    - pip
    - python >=3.5

  run:
    - python >=3.5
    - snowballstemmer

test:
  imports:
    - pydocstyle
  commands:
    - pydocstyle --version

about:
  home: https://github.com/PyCQA/pydocstyle
  license: MIT
  license_file: LICENSE-MIT
  summary: Python docstring style checker (formerly pep257)
  description: |
    pydocstyle is a static analysis tool for checking compliance with Python
    docstring conventions. pydocstyle supports most of PEP 257 out of the box,
    but it should not be considered a reference implementation.
    The framework for checking docstring style is flexible, and custom checks
    can be easily added, for example to cover NumPy docstring conventions.
    pydocstyle supports Python 3.4, 3.5, 3.6, and 3.7.
  doc_url: http://pydocstyle.readthedocs.org
  dev_url: https://github.com/PyCQA/pydocstyle

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - Nurdok
    - dopplershift
